import type { Metadata } from "next";
import { Cormorant_Garamond } from "next/font/google"; // Import Cormorant Garamond
import "./globals.css";

// Instantiate Cormorant Garamond
const cormorantGaramond = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["400", "700"], // Specify weights
  style: ["normal", "italic"], // Specify styles
  variable: "--font-cormorant-garamond", // CSS variable name
});

export const metadata: Metadata = {
  title: "Nestor Gutierrez Portfolio", // Updated title
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark"> {/* Added dark class to html for default dark theme */}
      <body
        className={`${cormorantGaramond.variable} antialiased font-sans`} // Use Cormorant Garamond and apply font-sans
      >
        <div
          className="fixed top-0 left-0 w-96 h-96 bg-amber-500/20 -translate-x-1/2 -translate-y-1/2 rounded-full blur-[150px] pointer-events-none -z-10"
          // w-96 h-96: size of the glow source
          // bg-amber-500/20: amber color (#F59E0B which is close to #FFA000) with 20% opacity
          // -translate-x-1/2 -translate-y-1/2: centers the glow origin more towards the corner
          // rounded-full: makes it circular
          // blur-[150px]: strong blur for diffusion
          // pointer-events-none: ensures it doesn't interfere with mouse events
          // -z-10: ensures it's behind content
        ></div>
        {children}
      </body>
    </html>
  );
}
